version: 2.1

executors:
  dotnet:
    docker:
      - image: microsoft/dotnet:2.1-sdk
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: circleci
          POSTGRES_PASSWORD: super-secret
          POSTGRES_DB: document_store_db 

    working_directory: ~/repo

    environment:
      - DATABASE_URL: postgres://circleci:super-secret@localhost:5432/document_store_db

jobs:
  build:
    executor: dotnet
    steps:
      - checkout
      - run: dotnet publish -c Release -o out

  test:
    executor: dotnet
    steps:
      - checkout
      - run: dotnet test

  deploy_staging:
    executor: dotnet
    steps:
      - checkout
      - run: scripts/deploy.sh staging

  deploy_dark_production:
    executor: dotnet
    steps:
      - checkout
      - run: scripts/deploy.sh production

  flip_production:
    executor: dotnet
    steps:
      - checkout
      - run: scripts/flip-dark-to-live.sh production

  revert_production:
    executor: dotnet
    steps:
      - checkout
      - run: scripts/flip-dark-to-live.sh production

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy_staging:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - hold_production_deploy:
          type: approval
          requires:
            - deploy_staging
      - deploy_dark_production:
          requires:
            - hold_production_deploy
      - hold_flip_production:
          type: approval
          requires:
            - deploy_dark_production
      - flip_production:
          requires:
            - hold_flip_production
      - hold_revert_production:
          type: approval
          requires:
            - flip_production
      - revert_production:
          requires:
            - hold_revert_production
